/**
 * Builds lighthouse/REPORT.md from the LHCI filesystem reports: median of the 3 runs per page and profile,
 * category scores, LCP / CLS / TBT, tool versions and run conditions.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import os from 'node:os'

const profiles = ['mobile', 'desktop']
const pages = { '/': 'Início', '/nft/nft-001': 'Detalhe do NFT' }
const categories = ['performance', 'accessibility', 'best-practices', 'seo']
const targets = { performance: 90, accessibility: 95, 'best-practices': 95, seo: 90 }
const median = (values) => [...values].sort((a, b) => a - b)[Math.floor(values.length / 2)]

const rows = []
let env
for (const profile of profiles) {
  const manifest = JSON.parse(readFileSync(`lighthouse/reports/${profile}/manifest.json`, 'utf8'))
  for (const [path, label] of Object.entries(pages)) {
    const runs = manifest.filter((m) => new URL(m.url).pathname === path)
    const lhrs = runs.map((r) => JSON.parse(readFileSync(r.jsonPath, 'utf8')))
    env ??= {
      lighthouse: lhrs[0].lighthouseVersion,
      chrome: lhrs[0].environment.hostUserAgent,
      settings: lhrs[0].configSettings,
    }
    const score = (c) => median(lhrs.map((l) => Math.round(l.categories[c].score * 100)))
    const metric = (id) => median(lhrs.map((l) => l.audits[id].numericValue))
    const representative = runs.find((r) => r.isRepresentativeRun) ?? runs[0]
    rows.push({
      profile,
      label,
      scores: Object.fromEntries(categories.map((c) => [c, score(c)])),
      lcp: metric('largest-contentful-paint'),
      cls: metric('cumulative-layout-shift'),
      tbt: metric('total-blocking-time'),
      report: representative.htmlPath.replace(/^.*lighthouse\//, ''),
    })
  }
}

const mark = (c, v) => (v >= targets[c] ? `${v}` : `**${v}** (meta ${targets[c]})`)
const table = [
  '| Perfil | Página | Performance | Accessibility | Best Practices | SEO | LCP | CLS | TBT | Relatório |',
  '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |',
  ...rows.map(
    (r) =>
      `| ${r.profile} | ${r.label} | ${categories.map((c) => mark(c, r.scores[c])).join(' | ')} | ${(r.lcp / 1000).toFixed(2)} s | ${r.cls.toFixed(3)} | ${Math.round(r.tbt)} ms | [html](${r.report}) |`,
  ),
].join('\n')

const generated = `<!-- Generated by scripts/lighthouse-report.mjs. Analysis below the marker is kept by hand. -->

## Resultados (mediana de 3 execuções)

${table}

## Ambiente e condições

- Lighthouse ${env.lighthouse} via @lhci/cli; ${env.chrome}
- Node ${process.version}; ${os.type()} ${os.release()} (${os.arch()}), ${os.cpus()[0].model}
- Build: \`pnpm build\` servido por \`pnpm preview\` (porta 4173), mocks MSW ativos no cenário \`default\` (latência 150-400 ms)
- Mobile: emulação padrão do Lighthouse (throttling simulado: RTT ${env.settings.throttling.rttMs} ms, ${env.settings.throttling.throughputKbps} Kbps, CPU ${env.settings.throttling.cpuSlowdownMultiplier}x); desktop: preset \`desktop\`
- 3 execuções por página e perfil; relatórios HTML/JSON em \`lighthouse/reports/<perfil>\`
`

let analysis = '\n<!-- analysis -->\n'
try {
  const current = readFileSync('lighthouse/REPORT.md', 'utf8')
  analysis = current.slice(current.indexOf('\n<!-- analysis -->'))
} catch {}
writeFileSync('lighthouse/REPORT.md', `# Auditoria Lighthouse\n\n${generated}${analysis}`)
console.log(table)
